fix compile with gcc 11 by adding missing '#include <deque>'
httpserver.cpp:73:10: error: ‘deque’ in namespace ‘std’ does not name a template type
   73 |     std::deque<std::unique_ptr<WorkItem>> queue;
      |          ^~~~~
httpserver.cpp:32:1: note: ‘std::deque’ is defined in header ‘<deque>’; did you forget to ‘#include <deque>’?

Signed-off-by: Scott S <ssimmons9999@gmail.com>